services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /app
    volumes:
      - ./storage:/app/storage
      - ./public:/app/public
    env_file:
      - .env.docker
    ports:
      - "6969:6969"
    restart: unless-stopped
    user: root
