services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "6969:6969"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DUCKDNS_API_TOKEN=fdc01a8b-dbaf-484a-aa0f-a48672d18fcf
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  caddy_data:
  caddy_config: